name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"  # 指定使用 pnpm 作为包管理器

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build  # 确保你的 package.json 中有 build 脚本

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"  # 指定构建输出目录

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
